alter table CARRIER_DELIVERY add constraint FK_CARRIER_DELIVERY_ON_CARRIER foreign key (CARRIER_ID) references CARRIER_CARRIER(ID);
create index IDX_CARRIER_DELIVERY_ON_CARRIER on CARRIER_DELIVERY (CARRIER_ID);
