-- begin CARRIER_TRUCK
alter table CARRIER_TRUCK add constraint FK_CARRIER_TRUCK_ON_CARRIER foreign key (CARRIER_ID) references CARRIER_CARRIER(ID)^
alter table CARRIER_TRUCK add constraint FK_CARRIER_TRUCK_ON_TRUCK_TYPE foreign key (TRUCK_TYPE_ID) references CARRIER_TRUCK_TYPE(ID)^
create unique index IDX_CARRIER_TRUCK_UNIQ_NUMBER_ on CARRIER_TRUCK (NUMBER_)^
create index IDX_CARRIER_TRUCK_ON_CARRIER on CARRIER_TRUCK (CARRIER_ID)^
create index IDX_CARRIER_TRUCK_ON_TRUCK_TYPE on CARRIER_TRUCK (TRUCK_TYPE_ID)^
-- end CARRIER_TRUCK
-- begin CARRIER_CARRIER
create unique index IDX_CARRIER_CARRIER_UNIQ_NAME on CARRIER_CARRIER (NAME)^
-- end CARRIER_CARRIER
