alter table CARRIER_HISTORY_COSTT add constraint FK_CARRIER_HISTORY_COSTT_ON_CARRIER foreign key (CARRIER_ID) references CARRIER_CARRIER(ID);
create index IDX_CARRIER_HISTORY_COSTT_ON_CARRIER on CARRIER_HISTORY_COSTT (CARRIER_ID);
