alter table CARRIER_HISTORY_COST add constraint FK_CARRIER_HISTORY_COST_ON_CARRIER foreign key (CARRIER_ID) references CARRIER_CARRIER(ID);
create index IDX_CARRIER_HISTORY_COST_ON_CARRIER on CARRIER_HISTORY_COST (CARRIER_ID);
